### ISSUE TITLE
services don't start - errors

### ISSUE THREAD

**Issue by machzqcq** [marcelbirkner/docker-ci-tool-stack#10]
1. I already had virtualbox 5.0.x with ubuntu trusty 14.02 image. I bumped up the RAM to 10gb
2. Installed docker and verified that I am able to pull images and start containers
3. git clone docker-ci-tool-stack
4. Installed docker-compose binary as per instructions [here](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-14-04)
5. I get the below errors when I ran "docker-compose up"

![ci_toolstack_error](https://cloud.githubusercontent.com/assets/6425159/12836720/4bd7f38e-cb89-11e5-82d7-2da400637c3a.png)  

Any help please?

**Comment by machzqcq** [comment]
So I did a little more troubleshooting. I tried to "docker build -t "mysonar" ." from inside the sonar folder. Seems like that is failing too.

```
Step 5 : EXPOSE 9092
 ---> Running in c5a32ad5d21c
 ---> fe283d49a0d3
Removing intermediate container c5a32ad5d21c
Step 6 : ENV SONARQUBE_JDBC_USERNAME sonar
 ---> Running in d5ad2d0a4507
 ---> bd5afe077050
Removing intermediate container d5ad2d0a4507
Step 7 : ENV SONARQUBE_JDBC_PASSWORD sonar
 ---> Running in e3cc07611fe9
 ---> df066ba7e5cf
Removing intermediate container e3cc07611fe9
Step 8 : ENV SONARQUBE_JDBC_URL jdbc:h2:tcp://localhost:9092/sonar
 ---> Running in 6b23ffc5efec
 ---> 91683ea6fa48
Removing intermediate container 6b23ffc5efec
Step 9 : ENV SONAR_VERSION 5.1.2
 ---> Running in 5afa71dc12ac
 ---> 3792ef4bebe5
Removing intermediate container 5afa71dc12ac
Step 10 : ENV SONAR_DOWNLOAD_URL https://sonarsource.bintray.com/Distribution
 ---> Running in 71792febcb1b
 ---> 1000aa5406b9
Removing intermediate container 71792febcb1b
Step 11 : RUN gpg --keyserver ha.pool.sks-keyservers.net --recv-keys F1182E81C792928921DBCAB4CFCA4A29D26468DE
 ---> Running in 8a5e27184208
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key D26468DE from hkp server ha.pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
The command '/bin/sh -c gpg --keyserver ha.pool.sks-keyservers.net --recv-keys F1182E81C792928921DBCAB4CFCA4A29D26468DE' returned a non-zero code: 2
pmacharl@osboxes:~/docker-ci-tool-stack/sonar$
```

**Comment by marcelbirkner** [comment]
Hi @machzqcq

the first problems looks like a networking issue **unable to resolve host ...**
You might want to check your VM's network settings.

In the second issue also seems to be related to network problems:
**gpg: keyserver timed out**

I have seen similar effects with company firewalls that conflict with docker network settings.

Greetings,
Marcel

**Comment by machzqcq** [comment]
Yes that was the problem. Firewall blocks ports. I was able to successfully install the stack on a mac at home. Thank you

**Comment by yoyobee1** [comment]
Hello @marcelbirkner .

I also got this issue, so which port should be open on our firewall will make it work ? 

Regards

**Comment by marcelbirkner** [comment]
Hi @yoyobee1 

you will find a couple of troubleshooting tips at the bottom of this README.md, https://github.com/codecentric/event-driven-microservices-platform

That's what I did, to fix the network problems. I will put the info in this repo's README.md as well.

Greetings,
Marcel

**Comment by yoyobee1** [comment]
@marcelbirkner  Thanks a lot, I also can resolve this issue by using change this line in Dockerfile of Sonar :+1: 
RUN gpg --keyserver ha.pool.sks-keyservers.net --recv-keys F1182E81C792928921DBCAB4CFCA4A29D26468DE

by 

RUN gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys F1182E81C792928921DBCAB4CFCA4A29D26468DE


And it work for me as well. 

Regards
