### ISSUE TITLE
Build / Start / Stop Docker Container in Jenkins Job

### ISSUE THREAD

**Issue by marcelbirkner** [marcelbirkner/docker-ci-tool-stack#11]
Add Docker-In-Docker Support to Jenkins Container

Update: **using docker.sock**

**Comment by gmacario** [comment]
Or perhaps https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

**Comment by marcelbirkner** [comment]
Hi @gmacario,

that's exactly what I will be doing using the docker.sock :-)

Greetings,
Marcel

**Comment by marcelbirkner** [comment]
added jobs for testing docker in jenkins
https://github.com/marcelbirkner/docker-ci-tool-stack/blob/master/jenkins/seedjobs/dockerAdminSeedJob.groovy
