### ISSUE TITLE
Fresh install on MacOs environment

### ISSUE THREAD

**Issue by halltony** [marcelbirkner/docker-ci-tool-stack#14]
SonarQube container doesn't come up properly.

Key errors seems to be:

sonar_1      | 2016.03.17 20:54:57 ERROR web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
sonar_1      | java.lang.IllegalStateException: Can not connect to database. Please check connectivity and settings (see the properties prefixed by 'sonar.jdbc.').

**Comment by marcelbirkner** [comment]
Hi @halltony 

can you try it again. I replaced the deprecated Links feature with "docker network". 
I also added a missing depends_on relation.

Greetings,
Marcel

**Comment by halltony** [comment]
Hi Marcel,

This has improved the situation how ever the Git and Selenium Grid components didn't appear to be accessible when I tried it last night. I need to have another look tonight before confirming the issue. 

I'll get back to you.

Regards

-t
