### ISSUE TITLE
gitlab --link still required

### ISSUE THREAD

**Issue by monochromec** [marcelbirkner/docker-ci-tool-stack#18]
Docker version 11.0.0 still requires 

"links:
    - redis:redisio"

in the gitlab section of docker-composer.yml. Otherwise the gitlab container will stop after unsuccessfully trying to ping the redis container in /sbin/entrypoint.sh

**Comment by mercuriete** [comment]
hi, i am using docker tools 1.11.1

This bug its happening to me as well.

gitlab output:

Initializing logdir...
Initializing datadir...
Generating OpenSSH host keys... RSA1 RSA DSA ECDSA ED25519 
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database.................
Configuring gitlab::redis...........................................................

and then dies.

**Comment by nezhar** [comment]
#20 changing REDIS_HOST to the name of the service should also work

**Comment by marcelbirkner** [comment]
Thanks for your feedback @monochromec 

I will update to the official GitLab docker container soon. Therefore this fix won't be necessary anymore.
Official GitLab Image: https://hub.docker.com/r/gitlab/gitlab-ce/

Greetings,
Marcel
