### ISSUE TITLE
Unsupported config option for services service: 'nodechrome'

### ISSUE THREAD

**Issue by adrianobr** [marcelbirkner/docker-ci-tool-stack#21]
docker compose-up
Unsupported config option for services service: 'nodechrome'
root@pmo:/home/sysmo/docker/docker-ci-tool-stack# docker-compose -v
docker-compose version: 1.3.1
CPython version: 2.7.10
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015

**Comment by marcelbirkner** [comment]
Duplicate of #15 

Please upgrade Docker Compose.
