### ISSUE TITLE
ERROR: Service 'nexus' failed to build (/bin/sh: wget: command not found)

### ISSUE THREAD

**Issue by Tset-Noitamotua** [marcelbirkner/docker-ci-tool-stack#22]
Hi, 

when following this turorial at home everything works nice. But I'm stuck on Step 8 (see below) when doing it on a corporate machine behind a proxy. 

I already configured proxy setting as described here: [Docker FAQs](https://docs.docker.com/faqs/troubleshoot/#http-proxies-and-connectivity-errors).  Searching and pulling images works, e.g. `docker search ubuntu` or `docker run hello-world`. I also tried what´s described in your [Troubleshooting.md](https://github.com/marcelbirkner/docker-ci-tool-stack/blob/master/Troubleshooting.md)

My System: Windows 7, 64bit, DockerToolbox 1.11.1b

What does that error mean and how can I solve it?
Appreciate any help.

![image](https://cloud.githubusercontent.com/assets/5635462/15607680/12c6eade-2415-11e6-992d-6e1af75b1504.png)

```shell
$ docker-compose up
Building nexus
Step 1 : FROM centos:6
 ---> ae6154bcd445
Step 2 : MAINTAINER Marcel Birkner <marcel.birkner@codecentric.de>
 ---> Using cache
 ---> a48c92ef67ba
Step 3 : USER root
 ---> Using cache
 ---> 945bdcd112ec
Step 4 : RUN yum -y update;     yum clean all
 ---> Using cache
 ---> d01868d28486
Step 5 : RUN yum -y install java-1.7.0-openjdk-devel     which     telnet     unzip     openssh-server
    sudo     openssh-clients     iputils     iproute     httpd-tools     wget     tar;     yum clean al
l
 ---> Using cache
 ---> efd1c0f08775
Step 6 : ENV JAVA_HOME /usr/lib/jvm/jre
 ---> Using cache
 ---> 6bee3748b5d0
Step 7 : RUN mkdir -p /opt/sonatype-nexus /opt/sonatype-work
 ---> Using cache
 ---> 2b259741336e
Step 8 : RUN wget -O /tmp/nexus-latest-bundle.tar.gz http://download.sonatype.com/nexus/oss/nexus-2.12.
0-01-bundle.tar.gz
 ---> Running in 338c58376ec3
/bin/sh: wget: command not found
ERROR: Service 'nexus' failed to build: The command '/bin/sh -c wget -O /tmp/nexus-latest-bundle.tar.gz
 http://download.sonatype.com/nexus/oss/nexus-2.12.0-01-bundle.tar.gz' returned a non-zero code: 127```

**Comment by Tset-Noitamotua** [comment]
I was able to find a workaround by modifying [line 36 of Dockerfile](https://github.com/marcelbirkner/docker-ci-tool-stack/blob/master/nexus/Dockerfile#L36) in `nexus`-folder from
`RUN wget -O /tmp/nexus-latest-bundle.tar.gz http://download.sonatype.com/nexus/oss/nexus-2.12.0-01-bundle.tar.gz`
to
`ADD http://download.sonatype.com/nexus/oss/nexus-2.12.0-01-bundle.tar.gz /tmp/nexus-latest-bundle.tar.gz`

But now I´m facing the next issue which I have no solution for so far:

![image](https://cloud.githubusercontent.com/assets/5635462/15616310/3b7b27c8-2443-11e6-9d61-79033d9f23fd.png)

Suggestion from this [comment ](https://github.com/marcelbirkner/docker-ci-tool-stack/issues/10#issuecomment-209221502) (#10) unfortunately does not help in my case.

Any ideas?

**Comment by marcelbirkner** [comment]
Hi @Tset-Noitamotua 

this looks like an old error. Did you clone the latest version of the repository? The gpg checks are not in the latest Dockerfile for the Nexus container.

Greetings,
Marcel

**Comment by marcelbirkner** [comment]
See https://github.com/marcelbirkner/docker-ci-tool-stack/blob/master/nexus/Dockerfile

**Comment by Tset-Noitamotua** [comment]
@marcelbirkner  I cloned the latest version today. The last error is not from Nexus container, it is from sonar container which has some gpg stuff in its dockerfile.

Where to go from here?

**Comment by marcelbirkner** [comment]
Hi, 

you can either remove the conflicting gpg check. I am not sure why that fails for you.

Line 41: "	&& gpg --verify sonarqube.zip.asc \"

Or instead of building the sonar image yourself, you can add the already build sonar image from my docker hub repo to the docker-compose.yml. That will simply download the already build docker sonar image.

  image: mbirkner/docker-ci-tool-stack-sonar:1.2

Greetings,
Marcel

**Comment by Tset-Noitamotua** [comment]
Thank you. I will check this alternatives on monday on the corporate
machine. At home everything works out of the box.

Cheers
Tset

Marcel Birkner <notifications@github.com> schrieb am Sa., 28. Mai 2016 um
21:00:

**Comment by marcelbirkner** [comment]
Maybe this here will help as well. 

https://gurrier.wordpress.com/2010/10/02/downlolading-repo-keys-from-behind-a-corporate-firewall/

**Comment by Qambar** [comment]
I am also getting a similar error and i am neither behind any firewall and nor there are any gpg checks in new docker file so i wonder what could be causing it:

```
[2018-04-17T23:30:13+00:00] ERROR: Exception handlers complete
[2018-04-17T23:30:13+00:00] ERROR: Exception handlers complete
  Chef Client failed. 2 resources updated in 09 seconds
[2018-04-17T23:30:13+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2018-04-17T23:30:13+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2018-04-17T23:30:13+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-04-17T23:30:13+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
ERROR: Service 'nexus' failed to build: The command '/bin/sh -c curl -L https://www.getchef.com/chef/install.sh | bash     && /opt/chef/embedded/bin/erb /var/chef/solo.json.erb > /var/chef/solo.json     && chef-solo        --recipe-url ${NEXUS_REPOSITORY_MANAGER_COOKBOOK_URL}        --json-attributes /var/chef/solo.json     && rpm -qa *chef* | xargs rpm -e     && rpm --rebuilddb     && rm -rf /etc/chef     && rm -rf /opt/chefdk     && rm -rf /var/cache/yum     && rm -rf /var/chef' returned a non-zero code: 1

```
