### ISSUE TITLE
DOCKER FOR MAC non virtual box support?

### ISSUE THREAD

**Issue by ryanmmmmm** [marcelbirkner/docker-ci-tool-stack#30]
docker-compose up throws tons of errors when using Docker for Mac

ERROR: for sonardb  Cannot start service sonardb: Mounts denied:
The path /opt/postgres/data
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERROR: Encountered errors while bringing up the project.

**Comment by ryanmmmmm** [comment]
➜  docker-ci-tool-stack git:(master) docker-compose up
dockercitoolstack_gitlab_1 is up-to-date
Starting dockercitoolstack_sonardb_1
Starting dockercitoolstack_nexus_1
Starting dockercitoolstack_seleniumhub_1
Starting dockercitoolstack_nodeff_1
Starting dockercitoolstack_nodechrome_1
Starting dockercitoolstack_sonar_1
Starting dockercitoolstack_jenkins_1

ERROR: for jenkins  Cannot start service jenkins: Mounts denied:  more info.
.
hs /opt/jenkins and /usr/local/bin/docker
are not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for
ERROR: Encountered errors while bringing up the project.

**Comment by ryanmmmmm** [comment]
I get around these by setting them in Preferences but at the end i get this error:

➜  docker-ci-tool-stack git:(master) docker-compose up
dockercitoolstack_gitlab_1 is up-to-date
Starting dockercitoolstack_sonardb_1
Starting dockercitoolstack_nexus_1
Starting dockercitoolstack_seleniumhub_1
Starting dockercitoolstack_nodeff_1
Starting dockercitoolstack_nodechrome_1
Starting dockercitoolstack_sonar_1
Starting dockercitoolstack_jenkins_1

ERROR: for jenkins  Cannot start service jenkins: mkdir /usr/local/bin/docker: file exists
ERROR: Encountered errors while bringing up the project.

**Comment by ryanmmmmm** [comment]
so this is trying to overwrite my mac path with a new installation of docker?  

any suggestions on what to do here?

**Comment by marcelbirkner** [comment]
Hi @ryanmmmmm,

I am using a MacBook Pro as well, with 16GB RAM.
I have tested the setup with the Docker Toolbox.

Did you try that instead of Docker for Mac? 
That explains the mount problem, since **/usr/local/bin/docker** is installed by the Docker Toolbox.

Greetings,
Marcel

**Comment by nishi-nigam** [comment]
Hi Marcel, 

Good day. Firstly, thank you for putting up such an interesting article. I've tried to get this running on a MacBook Pro (13-inc, 2016 model), running MacOS High Sierra. After adding the File Sharing preferences, I am still getting the "Mounts denied" error via both the "Docker Toolbox" option and the Docker for Mac option. Can you please help? 

Here are my logs: 

mymac:docker-ci-tool-stack $ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

$ sudo docker-compose up
dockercitoolstack_gitlab_1 is up-to-date
Starting dockercitoolstack_sonardb_1 ... 
Starting dockercitoolstack_sonardb_1
Starting dockercitoolstack_nexus_1 ... 
Starting dockercitoolstack_sonardb_1 ... done
Starting dockercitoolstack_sonar_1 ... 
Starting dockercitoolstack_sonar_1 ... done
Starting dockercitoolstack_jenkins_1 ... 
Starting dockercitoolstack_jenkins_1 ... error

ERROR: for dockercitoolstack_jenkins_1  Cannot start service jenkins: Mounts denied: EOF

ERROR: for jenkins  Cannot start service jenkins: Mounts denied: EOF
ERROR: Encountered errors while bringing up the project.

Any help will be appreciated. 

Thanks
Nishi

**Comment by raner** [comment]
I'm running into the same "Mounts denied: EOF" problem as @nishi-nigam -- any pointers how to diagnose what's going wrong here?
