### ISSUE TITLE
cannot run when using virtualbox

### ISSUE THREAD

**Issue by ryanmmmmm** [marcelbirkner/docker-ci-tool-stack#31]
I am getting the following error when using virtualbox:

➜  docker-ci-tool-stack git:(master) docker-compose up
Building jenkins
Step 1 : FROM jenkins:2.7.1
 ---> 2aae9163902e
Step 2 : USER root
 ---> Using cache
 ---> 80a5d5b2420e
Step 3 : RUN apt-get update       && apt-get install -y sudo curl      && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 5159063c3440
Step 4 : RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
 ---> Using cache
 ---> 7a63834f5416
Step 5 : RUN curl -sSL -O https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz && tar -xvzf docker-latest.tgz
 ---> Using cache
 ---> f20613d27f10
Step 6 : RUN mv docker/\* /usr/bin/
 ---> Using cache
 ---> d9ab5e384f23
Step 7 : USER jenkins
 ---> Using cache
 ---> 8893aef9d54a
Step 8 : COPY plugins.txt /var/jenkins_home/plugins.txt
 ---> Using cache
 ---> e8c2ed98da03
Step 9 : RUN /usr/local/bin/plugins.sh /var/jenkins_home/plugins.txt
 ---> Running in fd4d41f02996
Analyzing war: /usr/share/jenkins/jenkins.war
Downloading ansicolor:0.4.2
Downloading ant:1.3
Downloading antisamy-markup-formatter:1.5
Downloading authentication-tokens:1.3
Downloading build-pipeline-plugin:1.5.3.1
Downloading chucknorris:1.0
Downloading clone-workspace-scm:0.6
Downloading cloudbees-credentials:3.3
Downloading cloudbees-folder:5.12
Downloading conditional-buildstep:1.3.5
Downloading config-file-provider:2.11
Downloading credentials:2.1.4
Downloading dashboard-view:2.9.10
Downloading docker-build-publish:1.3.1
Downloading docker-commons:1.4.0
Downloading external-monitor-job:1.5
Downloading git:2.5.2
Downloading git-client:1.19.7
Downloading github:1.19.3
Downloading github-api:1.76
Downloading groovy:1.29
curl: (52) Empty reply from server
ERROR: Service 'jenkins' failed to build: The command '/bin/sh -c /usr/local/bin/plugins.sh /var/jenkins_home/plugins.txt' returned a non-zero code: 52
➜  docker-ci-tool-stack git:(master) docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/rmedlin/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell:

**Comment by marcelbirkner** [comment]
I am using Docker 1.12 and VirtualBox 5.0.30 on my MacBook (Sierra).
Try the latest updates and let me know if it works for you.
