### ISSUE TITLE
settings.xml or Global settings.xml which one is used and what is the difference 

### ISSUE THREAD

**Issue by ashishsoni** [marcelbirkner/docker-ci-tool-stack#32]
Please help which file is being used settings.xml or Global settings.xml

**Comment by marcelbirkner** [comment]
Hi @ashishsoni 

in the conference-app-1-ci Job I am using the Global settings.xml.

Go to -> Job Config -> Maven Target -> Advanced

There you will find the reference.
http://192.168.99.100:18080/view/Conference%20App/job/conference-app-1-ci/configure
