### ISSUE TITLE
nodeff_1 and nodechrome_1 Connection refused

### ISSUE THREAD

**Issue by BeckerFrank** [marcelbirkner/docker-ci-tool-stack#33]
Today I in start the setup an I get the following errors:
nodechrome_1   | 12:52:52.184 INFO - Couldn't register this node: The hub is down or not responding: Connect to seleniumhub:80 [seleniumhub/172.19.0.4] failed: Connection refused
nodeff_1       | 12:52:52.235 INFO - Couldn't register this node: The hub is down or not responding: Connect to seleniumhub:80 [seleniumhub/172.19.0.4] failed: Connection refused

My environment is a macbook pro with the latest macOS and virtual box

**Comment by thomastik** [comment]
Same with me running it on an Ubuntu server hosted on Azure

**Comment by marcelbirkner** [comment]
Moved the Seleniums Hub + Nodes to a separate docker-compose-selenium.yml file.
Use the following command in case you want to use Selenium as well. 

> docker-compose -f docker-compose-selenium.yml up
