### ISSUE TITLE
README.md: Getting started change git clone error

### ISSUE THREAD

**Issue by BeckerFrank** [marcelbirkner/docker-ci-tool-stack#34]
Please change the 

git clone git@github.com:marcelbirkner/docker-ci-tool-stack.git

to

git clone https://github.com/marcelbirkner/docker-ci-tool-stack.git

or you get the following error:
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by nordri** [comment]
You need to add ssh-key to your account in order to use the first one.

**Comment by marcelbirkner** [comment]
@BeckerFrank / @nordri 
Thanks for the input. I added your comments to the README
