### ISSUE TITLE
Dockerfile missing

### ISSUE THREAD

**Issue by hmeftah** [marcelbirkner/docker-ci-tool-stack#35]
Hi 
Many thanks for your great CI tools stack, we ran a bunch of tests it seems a dockerfile is missing when starting the Jenkins job  "conference-app-monitoring-3-docker-build" 
Do you have any clue about that ?
Regards
Herve

**Comment by marcelbirkner** [comment]
@hmeftah 

fixed it, https://github.com/codecentric/conference-app/blob/master/monitoring/Dockerfile
thanks for the feedback :-)

Marcel
