### ISSUE TITLE
Nexus url for releases is wrong

### ISSUE THREAD

**Issue by kom-dev** [marcelbirkner/docker-ci-tool-stack#36]
Hi Marcel,

This url `http://nexus:8081/content/repositories/releases/` doesn't work.

The right one is `http://nexus:8081/nexus/content/repositories/releases/`

I think this [commit](https://github.com/marcelbirkner/docker-ci-tool-stack/commit/76623288a66989cef6377c5b9351206c8132a2d0#diff-12bc30d28dad9514b61402768f2682ff) was a little bit wild ;-)

**Comment by marcelbirkner** [comment]
@kom-dev 

should be fixed now
