### ISSUE TITLE
selenium nodes on Linux 

### ISSUE THREAD

**Issue by dlaub3** [marcelbirkner/docker-ci-tool-stack#37]
The Selenium nodes didn't register by default in Linux. I added this to the docker-compose.yml for each nodeff and nodechrome.  See the comment here: https://hub.docker.com/r/selenium/hub/ 

```
  environment:
   - HUB_PORT_4444_TCP_ADDR=seleniumhub
   - HUB_PORT_4444_TCP_PORT=4444

```

**Comment by marcelbirkner** [comment]
Thanks for the feedback
