### ISSUE TITLE
gitlab always restarting in mac native

### ISSUE THREAD

**Issue by joedayz** [marcelbirkner/docker-ci-tool-stack#38]
Error executing action `run` on resource 'ruby_block[directory resource: /var/opt/gitlab/git-data/repositories]'

I have problems with sonar and gitlab

CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                         PORTS                                NAMES
312bdd4218ad        dockercitoolstack_jenkins      "/bin/tini -- /usr/lo"   9 minutes ago       Up 9 minutes                   50000/tcp, 0.0.0.0:18080->8080/tcp   dockercitoolstack_jenkins_1
dc74ed29ea70        dockercitoolstack_sonar        "/opt/sonarqube/run.s"   9 minutes ago       Exited (0) 9 minutes ago                                            dockercitoolstack_sonar_1
cb3f4318ef3d        gitlab/gitlab-ce:8.14.4-ce.0   "/assets/wrapper"        9 minutes ago       Restarting (1) 5 seconds ago                                        dockercitoolstack_gitlab_1
6dfeafd6fb04        dockercitoolstack_nexus        "/bin/sh -c 'java   -"   9 minutes ago       Up 9 minutes                   0.0.0.0:18081->8081/tcp              dockercitoolstack_nexus_1
75d1dabc064b        postgres                       "/docker-entrypoint.s"   9 minutes ago       Up 9 minutes                   5432/tcp                             dockercitoolstack_sonardb_1

**Comment by justinbleach** [comment]
I had the same issue. I had to run the following on the data directory within /opt/gitlab

sudo chmod 0777 data

gitlab needs the data directory to be accessible by everyone according to this issue I found Googling: https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1601

**Comment by marcelbirkner** [comment]
I disabled gitlab by default, since all example jobs use github repositories anyway. The Gitlab Docker configuration itself is getting more and more complex. Please refer to https://hub.docker.com/r/gitlab/gitlab-ce/

**Comment by devicemanager** [comment]
sudo chmod g+s /opt/gitlab/data/git-data/repositories/ in macOS
