### ISSUE TITLE
Selenium Grid, Conference App

### ISSUE THREAD

**Issue by naqsh01** [marcelbirkner/docker-ci-tool-stack#40]
Hi Marcel, 

I was able to start your containers but unable to get the following: 
- Selenium Grid	http://${docker-machine ip default}:4444/grid/console
- Conference App	http://${docker-machine ip default}:48080/currentSessions

Am I suppose to build something in Jenkins in order to see those links active? 

Once I have the containers up -- how should I navigate this demo?

Thanks,
Aliusa

**Comment by zene22** [comment]
The seleniumhub has to be started separately with "docker-compose -f docker-compose-selenium up". The conferenceApp builds (automagically ;) ) in jenkins and is also deployed from there in a separate docker Container.

**Comment by marcelbirkner** [comment]
`docker-compose -f docker-compose-selenium.yml up`
