### ISSUE TITLE
Jenkins issue

### ISSUE THREAD

**Issue by keer2012** [marcelbirkner/docker-ci-tool-stack#41]
I got this issue on my mac.
ERROR: for jenkins  Cannot start service jenkins: error while creating mount source path '/usr/local/bin/docker': chown /usr/local/bin/docker: no such file or directory

**Comment by marcelbirkner** [comment]
Where is your docker binary installed? You might have to adjust that path in the docker compose yml.

**Comment by trumhemcut** [comment]
I face the same issue:
➜  devops docker-compose up
Removing jenkins
gitlab is up-to-date
Recreating 09c82acaad92_09c82acaad92_jenkins

ERROR: for jenkins  Cannot start service jenkins: error while creating mount source path '/usr/local/bin/docker': chown /usr/local/bin/docker: no such file or directory
ERROR: Encountered errors while bringing up the project.
➜  devops which docker
/usr/local/bin/docker

**Comment by Pomax** [comment]
Why was this issue closed? Did @keer2012 fix it? If so, can he/she please let the world know **how** because this is a massive pain in the backside.
