### ISSUE TITLE
Update Jenkins

### ISSUE THREAD

**Issue by chg1995** [marcelbirkner/docker-ci-tool-stack#44]
Hi, how can I update Jenkins? It shows me a message that is a new version available.

**Comment by marcelbirkner** [comment]
Hi @chg1995 

you need to update the Jenkins Dockerfile and build the image again.
https://github.com/marcelbirkner/docker-ci-tool-stack/blob/master/jenkins/Dockerfile

Greetings,
Marcel

**Comment by chg1995** [comment]
Thank you very much for your quick response.
Greetings.
