### ISSUE TITLE
is it possible to add more service?

### ISSUE THREAD

**Issue by tremkonzah** [marcelbirkner/docker-ci-tool-stack#47]
Hello

could we have soapui too? and add more selenium node? (internet explorer, edge, opera and safari)?

thanks

**Comment by jlopezjuy** [comment]
Hello, CI is great, now, you can add mysql? or how i can add mysql to this docker image?

**Comment by marcelbirkner** [comment]
@jlopezjuy 
to add MySQL as DB have a look at https://hub.docker.com/_/mysql/

@tremkonzah 
to add different browsers only the following are currently supported, https://hub.docker.com/u/selenium/
IE won't work with docker
