### ISSUE TITLE
Jenkins container failing to build with error

### ISSUE THREAD

**Issue by DarrenRatcliffe** [marcelbirkner/docker-ci-tool-stack#48]
On a clean Ubuntu 16.04 Docker host (running version: 17.05.0-ce, build 89658be) when running docker-compose (version: 1.11.2, build dfed245) up. I am getting this error:

```
ERROR: for jenkins  Cannot start service jenkins: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/usr/local/bin/docker\\\" to rootfs \\\"/data/docker/aufs/mnt/14891bf80ee3497930c45f0ef94adcb75e0cb664e93ad62812fd595027e5e743\\\" at \\\"/data/docker/aufs/mnt/14891bf80ee3497930c45f0ef94adcb75e0cb664e93ad62812fd595027e5e743/usr/bin/docker\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```
I also tried this on Docker for Windows and got the same issue?

**Comment by wkonecny** [comment]
@DarrenRatcliffe if you are running this from Ubuntu, you are probably using docker native. Run this first and then try `docker-compose up` (first run `docker-compose down`) again:
https://github.com/marcelbirkner/docker-ci-tool-stack/blob/master/docker-compose.yml.native-docker-fix.sh

I am not a Windows user, so I unfortunately cannot help you with that.
