### ISSUE TITLE
Use cases example

### ISSUE THREAD

**Issue by vikasgubbi** [marcelbirkner/docker-ci-tool-stack#49]
Hi,

Do you have Use cases examples for this image.

Regards,

**Comment by marcelbirkner** [comment]
I use this repository for workshops. This is not production ready.
For production I use a configuration management tool like Ansible to provision the docker container.

See https://www.slideshare.net/MarcelBirkner/continuous-delivery-in-enterprise-environments-using-docker-ansible-and-jenkins
