### ISSUE TITLE
Error starting setup.sh

### ISSUE THREAD

**Issue by ralfebert1** [marcelbirkner/docker-ci-tool-stack#50]
Hi,

I've installed your project using 
 git clone https://github.com/marcelbirkner/docker-ci-tool-stack.git
and set execute permission for the file setup.sh.

starting the script I get the messages behind:

```
ralf@Entwicklungssystem:~/Downloads/docker-ci-tool-stack$ ./setup.sh
Create docker machine
./setup.sh: 12: ./setup.sh: docker-machine: not found
Setup environment
./setup.sh: 15: ./setup.sh: docker-machine: not found
Checkout Git Repository
Klone nach 'docker-ci-tool-stack' ...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
./setup.sh: 19: cd: can't cd to docker-ci-tool-stack
Startup Docker Compose
./setup.sh: 22: ./setup.sh: docker-compose: not found
ralf@Entwicklungssystem:~/Downloads/docker-ci-tool-stack$ 

```
How can I solve this problem? I'm using docker-ce on ubuntu trusty, the output of docker --version is

`Docker version 17.06.0-ce, build 02c1d87`

best regards
Ralf Ebert

**Comment by eitsch** [comment]
Hi Ralf,

> [...] How can I solve this problem? [...] 

i do not know much about using git on linux but maybe you can solve it by either setting up your github credentials correctly or by replacing line 18 in setup.sh with the following line:

`git clone https://github.com/marcelbirkner/docker-ci-tool-stack.git`


You might want to [expand your knowledge](https://www.google.de/search?q=github+Permission+denied+(publickey).+fatal:+Could+not+read+from+remote+repository.) on those two lines:

> Permission denied (publickey).
> fatal: Could not read from remote repository.

The comments [on this SO answer](https://stackoverflow.com/a/12940681) seem to be able to deliver insights concerning setting up SSH vs using HTTPS urls for git.

cheers
H
