### ISSUE TITLE
SonarQube won't start, possible ElasticSearch issue

### ISSUE THREAD

**Issue by jvogtherr** [marcelbirkner/docker-ci-tool-stack#54]
SonarQube wont start properly. This is the error message that I see in the logs:

`
2017.10.30 14:13:33 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2017.10.30 14:13:34 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2017.10.30 14:13:34 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: 
/opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
Warning: Ignoring JAVA_OPTS= -Duser.country=DE -Duser.language=de -Duser.timezone=Europe/Berlin
Please pass JVM parameters via ES_JAVA_OPTS instead
2017.10.30 14:13:34 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2017.10.30 14:13:40 INFO  app[][o.e.p.PluginsService] no modules loaded
2017.10.30 14:13:40 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2017.10.30 14:14:04 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 1
2017.10.30 14:14:04 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2017.10.30 14:14:04 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
`

The other containers work fine. It seems like ElasticSearch is having problems starting up. Any ideas how to fix this?

**Comment by marcelbirkner** [comment]
I can not reproduce this issue. Can you throw away all container/volumes and try it again?
