### ISSUE TITLE
www.slideshare.net resource in README.md is unavaliable

### ISSUE THREAD

**Issue by cheprus** [marcelbirkner/docker-ci-tool-stack#62]
Hi, Marcel,
The link in README.md is inaccessible https://www.slideshare.net/MarcelBirkner/continuous-delivery-in-enterprise-environments-using-docker-ansible-and-jenkins

**Comment by localsnet** [comment]
Probably in your country this resource was blocked, so use vpn (Opera
browser has embedded)

**Comment by marcelbirkner** [comment]
Hi @cheprus,

I attached the presentation to this ticket. 

[2017-javaland-presentation-170522125019.pdf](https://github.com/marcelbirkner/docker-ci-tool-stack/files/2290293/2017-javaland-presentation-170522125019.pdf)

Greetings,
Marcel

**Comment by localsnet** [comment]
Your provider blocked it. So use workaround (VPN/proxy/etc)

**Comment by achepur** [comment]
Thank you. This was the only solution I have found - using VPN.

**Comment by localsnet** [comment]
Not at all. I've  had  the same in my country.

2018-08-16 12:34 GMT+03:00 achepur <notifications@github.com>:
