### ISSUE TITLE
Sonar-runner and the tool stack

### ISSUE THREAD

**Issue by reedflinch** [marcelbirkner/docker-ci-tool-stack#8]
Hi @marcelbirkner, I am trying to integrate SonarSource's sonar-runner scanning tool with your tool stack and I'm having quite a few issues.  Specifically, when I run sonar-runner from its own container, I will consistently get a "cannot connect to database" error.  All ports should be exposed correctly.

Might you be able to help me by explaining how you configured Maven to scan your code?

**Comment by marcelbirkner** [comment]
Hi,

The Sonar Maven Settings are all stored in the settings.xml. For details see https://github.com/marcelbirkner/docker-ci-tool-stack/blob/master/jenkins/config/maven-global-settings-files.xml

In the Jenkins Sonar Job i am simple running mvn sonar:Sonar

Does that help you?

Marcel

**Comment by reedflinch** [comment]
Properly configuring the sonar-project.properties, sonar.properties and sonar-runner.properties did the trick.  Thank you for making this available!
